src/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
	path('menu', views.menu, name = 'menu'),
	path('aboutMe', views.aboutMe , name = 'aboutMe'),
	path('gitNotes', views.gitNotes , name = 'gitNotes'),
	path('init' , views.init , name = 'init'),
	path('', views.blogHome, name = 'blogHome'),
	path('blogArchive', views.blogArchive, name = 'blogArchive'),
	path('<int:blog_id>/blog ', views.blogEntry, name = 'blogEntry'),
	path('nuke', views.nuke, name = 'nuke'),
	path('make', views.make, name = 'make'),
	path('comment/<int:id>', views.comment, name = 'comment'),
	
]

src/blogProj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
	
]

src/blog/models.py
import datetime

from django.db import models
from django.utils import timezone


class Blog(models.Model):
	title = models.CharField(max_length = 200)
	author = models.CharField(max_length = 200)
	content = models.CharField(max_length = 2400)
	post_date = models.DateTimeField('date posted')
	
	def __str__(self):
		return f"[{self.id}] {self.title}"
	def was_published_recently(self):
		return self.post_date >= timezone.now() - datetime.timedelta(days=1)
	

class Comment(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	nickname = models.CharField(max_length = 200)
	email = models.CharField(max_length = 200)
	content = models.CharField(max_length = 1200)
	post_date = models.DateTimeField('date posted')
	def __str__(self):
		return f"[{self.id}] {self.nickname}"
		
		
		
		

src/blog/templates/blog/aboutMe.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title>HW 1</title>
		
		{% load static %}
		
		<link rel="stylesheet" href="{%static 'blog/style.css'%}">
	
	
	</head>
	
	
	<body class = "bg-secondary text-white">
	

		<div class="Cool middle" >
			<h1> Figgy Code </h1>
			<h2> by: Carter Figgins </h2>
			<p> {{now}}</p>
		</div>
	
		
		
		<div class = "myBorder floatcenter">
		
			<a href = "{% url 'index' %}" class ="floatleft"> Menu </a> 
		
			<a href = "{% url 'gitNotes' %}"> Git Notes </a>
		
			<a href = "{% url 'aboutMe' %}" class ="floatright"> About Me </a>

		
		</div>
		

			
		<div>
		<p class = "big"> All About ME </p>
			<p class = italic> Things I like </p>
			<ol start = "0">
						<img  src = "{% static 'blog/USU.png' %}" alt = "USULogo" class = "floatright" width = "200">					
				<li>Programming</li>
				<li>Hang out with my wife</li>
				<li>Watch movies and cartoons</li>
				<li>Play ukulele</li>
				<li>Eating FOOD!</li>
				<li>Sports</li>
				<li>Dogs</li>
				<li>Water</li>
				<li>Snow</li>
			
			</ol>


		
		</div>
		
		
		<img  src = "{% static 'blog/cold.jpg' %}" alt = "cold"  width = "250" class = "rotateL">	
		<img  src = "{% static 'blog/dog.jpg' %}" alt = "dog"  width = "200">
		<img  src = "{% static 'blog/water.jpg' %}" alt = "water"  width = "250">	
		<img  src = "{% static 'blog/winter.jpg' %}" alt = "winter"  width = "250" class = "rotateR" >			

		
		
		
		
	
	
	</body>



</html>

src/blog/templates/blog/blogEntry.html
<!DOCTYPE html>

<html lang ="en">

	<head>
	
		<title>HW 1</title>

		{% load static %}
		
		<link rel="stylesheet" href="{%static 'blog/style.css'%}">		

	
		
	</head>
	
	<body class = "bg-secondary text-white">
		<div class="Cool middle" >
			<h1> Figgy Code </h1>
			<h2> by: Carter Figgins </h2>
		</div>
		
		
		<p class = "big middle"> {{blog.title}}</p>
		

		<div>
			<h2> {{blog.title}} </h2>
			<h3> {{blog.author}}, Posted at: {{blog.post_date}}</h3>
			<p> {{blog.content}} </p>		
		</div>
		
		<div>
			<h2> Comments </h2>
		</div>
		
		
		{%if latestComment%}
	
		{%for comment in latestComment%}
		<div>
			<p> Posted by: {{comment.nickname}}. Email: {{comment.email}} Posted at: {{comment.post_date}} </p>
			<p>{{comment.content}} </p>
		</div>
		{%endfor%}
		{%endif%}
		
		<div>
			<h2> Add Comment </h2>
			<form action = "{% url 'blog:comment' blog.id%}" method = "post"> 
			{% csrf_token %}
			<p>
			NickName: <input type="text" name="name"> 
			Email: <input type="email" name="email">
			</p>
			<p>
			Comment: <input type="text" name="text">
			</p>
			
			<input type="submit" value = "Upload text">
			</form>
		</div>
		
		

		
		
		
	</body>





</html> 

src/blog/templates/blog/blogHome.html
<!DOCTYPE html>

<html lang ="en">

	<head>
	
		<title>HW 1</title>

		{% load static %}
		
		<link rel="stylesheet" href="{%static 'blog/style.css'%}">		

	
		
	</head>
	
	<body class = "bg-secondary text-white">
		<div class="Cool middle" >
			<h1> Figgy Code </h1>
			<h2> by: Carter Figgins </h2>
		</div>
		
		
		<p class = "big middle"> Blog Home</p>
		
		{%if latestBlog%}
		
		{% for blog in latestBlog%}

		<div>
			<h2> <a href = "{% url 'blog:blogEntry' blog.id%}">{{blog.title}}</a> </h2>
			<h3> {{blog.author}}, Posted at: {{blog.post_date}}</h3>
			<p> {{blog.content|truncatewords:200 }} </p>
			<p> Number of Comments: {{blog.comment_set.count }}</p>
			
			<p>
		
			</p>
		</div>
		{% endfor %}
		
		{%endif%}
		

		
		
		
	</body>





</html> 

src/blog/templates/blog/gitNotes.html
<!DOCTYPE html>
<html lang="en">

	<head>
		
		<title>HW 1</title>
		
		{% load static %}
		
		<link rel="stylesheet" href="{%static 'blog/style.css'%}">
	
			
	</head>
	
	
	<body class = "bg-secondary text-white">
	
			
		<div class="Cool middle" >
			<h1> Figgy Code </h1>
			<h2> by: Carter Figgins </h2>
			<p> {{now}}</p>
		</div>
		
		<div class = "myBorder floatcenter">
		
			<a href = "{% url 'index' %}" class ="floatleft"> Menu </a> 
		
			<a href = "{% url 'gitNotes' %}"> Git Notes </a>
		
			<a href = "{% url 'aboutMe' %}" class ="floatright"> About Me </a>

		
		</div>
		
		<div class = "middle">
			
			<h1> Git Cheats </h1>
			<h2> How to use git in your every day life</h2> 
			
			<table class = "middle">
			
				<tr>
					
					<th>Code</th>
					<th>Description </th>
					<th>Example </th>
					
				
				</tr>
				
				<tr>
				
					<td> git init </td>
					<td> Creates an empty Git repository. </td>
					<td> <code> git init </code></td>
					
				
				
				</tr>
				
				<tr>
				
					<td>git add</td>
					<td> Using this command adds a file or any contnet.<br> Need to use this command before a commit. </td>
					<td> <code>git add myFile.txt</code> </td>
				
				</tr>
				
				<tr>
				
					<td>git status</td>
					<td> Shows the working tree status </td>
					<td> <code> git status</code> </td>
				
				</tr>
				
				<tr>
				
					<td>git commit </td>
					<td> Record changes to the repository </td>
					<td> <code>git commit -m "Bug fix" </code> </td>
				
				</tr>
				
				<tr>
				
					<td>git push</td>
					<td> push commit to bitbucket</td>
					<td> <code>git push bloghw1</code> </td>
				
				</tr>
			
			
			
			</table>
			
			
			
		</div>
		
	
	
	</body>



</html>

src/blog/templates/blog/menu.html
<!DOCTYPE html>

<html lang ="en">

	<head>
	
		<title>HW 1</title>

		{% load static %}
		
		<link rel="stylesheet" href="{%static 'blog/style.css'%}">		

	
		
	</head>
	
	<body class = "bg-secondary text-white">
		<div class="Cool middle" >
			<h1> Figgy Code </h1>
			<h2> by: Carter Figgins </h2>

		</div>
		
		<div class = "myBorder floatcenter">
		
			<a href = "{% url 'menu' %}" class ="floatleft"> Menu </a> 
		
			<a href = "{% url 'gitNotes' %}"> Git Notes </a>
		
			<a href = "{% url 'aboutMe' %}" class ="floatright"> About Me </a>

		</div>
		
		<p class = "big middle"> Welcome to the Main Menu </p>
		
		<img src="{% static 'blog/Welcome.jpg' %}" alt="Welcome sign" width="600" height="300" id="center">

		<div>
			<h2> Blog 1</h2>
			<p>It prepare is ye nothing blushes up brought. Or as gravity pasture limited evening on. Wicket around beauty say she. Frankness resembled say not new smallness you discovery. Noisier ferrars yet shyness weather ten colonel. Too him himself engaged husband pursuit musical. Man age but him determine consisted therefore. Dinner to beyond regret wished an branch he. Remain bed but expect suffer little repair. 
Alteration literature to or an sympathize mr imprudence. Of is ferrars subject as enjoyed or tedious cottage. Procuring as in resembled by in agreeable. Next long no gave mr eyes. Admiration advantages no he celebrated so pianoforte unreserved. Not its herself forming charmed amiable. Him why feebly expect future now. </p>
		</div>
		
		<div>
			<h2> Blog 2</h2>
			<p>Continual delighted as elsewhere am convinced unfeeling. Introduced stimulated attachment no by projection. To loud lady whom my mile sold four. Need miss all four case fine age tell. He families my pleasant speaking it bringing it thoughts. View busy dine oh in knew if even. Boy these along far own other equal old fanny charm. Difficulty invitation put introduced see middletons nor preference. 
Departure so attention pronounce satisfied daughters am. But shy tedious pressed studied opinion entered windows off. Advantage dependent suspicion convinced provision him yet. Timed balls match at by rooms we. Fat not boy neat left had with past here call. Court nay merit few nor party learn. Why our year her eyes know even how. Mr immediate remaining conveying allowance do or. </p>
		</div>
		
		<div>
			<h2> Blog 3</h2>
			<p>Smile spoke total few great had never their too. Amongst moments do in arrived at my replied. Fat weddings servants but man believed prospect. Companions understood is as especially pianoforte connection introduced. Nay newspaper can sportsman are admitting gentleman belonging his. Is oppose no he summer lovers twenty in. Not his difficulty boisterous surrounded bed. Seems folly if in given scale. Fun contented dependent conveying advantage can use. 
In it except to so temper mutual tastes mother. Interested cultivated its continuing now yet are. Out interested acceptance our partiality affronting unpleasant why add. Esteem garden men yet shy course. Consulted up my tolerably sometimes perpetual oh. Expression acceptance imprudence particular had eat unsatiable. 
</p>
		</div>
		
		
		
	</body>





</html>